/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EigenschaftenTransition.java
 *
 * Created on 11.11.2010, 16:38:03
 */

package gui;

import static gui.i18n.I18n.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import petrinetze.impl.Transition;

/**
 *
 * @author aas551
 */
public class FeatureTransition extends javax.swing.JFrame {

    /** Creates new form EigenschaftenTransition */
    public FeatureTransition() {
        initComponents();
        bApply.setText(get("apply"));
        bCancel.setText(get("cancel"));
        lName.setText(get("name"));
        lToken.setText(get("token"));
        this.setTitle(get("properties") + " abc");
        //Center
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        int middleHeight = screenSize.height/2;
        int middleWidth = screenSize.width /2;
        setLocation(middleWidth - this.getWidth()/2, middleHeight - this.getHeight()/2);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lId = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        bApply = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        lToken = new javax.swing.JLabel();
        spinToken = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lId.setText("ID");

        txtId.setText("22");

        lName.setText("Name");

        txtName.setText("Peter");

        bApply.setText("Übernehmen");

        bCancel.setText("Abbrechen");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        lToken.setText("Token");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lName)
                    .addComponent(lId)
                    .addComponent(lToken))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bApply))
                    .addComponent(txtId)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(spinToken, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lId)
                    .addComponent(txtId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lToken))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bApply)
                    .addComponent(bCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_bCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bApply;
    private javax.swing.JButton bCancel;
    private javax.swing.JLabel lId;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lToken;
    private javax.swing.JSpinner spinToken;
    private javax.swing.JLabel txtId;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

}
