/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainGUI.java
 *
 * Created on 19.11.2010, 09:32:30
 */
package gui;

import java.io.IOException;
import javax.swing.UIManager;


/**
 *
 * @author Niklas
 */
public class MainGUI extends javax.swing.JFrame {

    /** Creates new form MainGUI */
    public MainGUI() {
        initComponents();
        initLanguage("de","DE");
    }
    
    private void initLanguage(String lang,String lang2) {
        I18n.setLocale(lang, lang2);
        toggleButtonPlace.setText(I18n.translate("place")); // NOI18N
        toggleButtonTransition.setText(I18n.translate("transition"));
        toggleButtonEdge.setText(I18n.translate("edge"));
        buttonStep.setText(I18n.translate("step"));
        buttonSteps.setText(I18n.translate("steps"));
        toggleButtonPlay.setText(I18n.translate("play"));
        status.setText(I18n.translate("status"));
        fileMenu.setText(I18n.translate("file"));
        openMenuItem.setText(I18n.translate("open"));
        saveMenuItem.setText(I18n.translate("save"));
        saveAsMenuItem.setText(I18n.translate("saveas"));
        exitMenuItem.setText(I18n.translate("exit"));
        editMenu.setText(I18n.translate("edit"));
        cutMenuItem.setText(I18n.translate("cut"));
        copyMenuItem.setText(I18n.translate("copy"));
        pasteMenuItem.setText(I18n.translate("paste"));
        deleteMenuItem.setText(I18n.translate("delete"));
        languageMenu.setText(I18n.translate("language"));
        deutschMenuItem.setText(I18n.translate("german"));
        EnglishMenuItem.setText(I18n.translate("english"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        petriTools = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jToolBar1 = new javax.swing.JToolBar();
        toggleButtonPlace = new javax.swing.JToggleButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        toggleButtonTransition = new javax.swing.JToggleButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        toggleButtonEdge = new javax.swing.JToggleButton();
        jToolBar2 = new javax.swing.JToolBar();
        buttonStep = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jSpinner1 = new javax.swing.JSpinner();
        buttonSteps = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        toggleButtonPlay = new javax.swing.JToggleButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        status = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        languageMenu = new javax.swing.JMenu();
        deutschMenuItem = new javax.swing.JMenuItem();
        EnglishMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Petrinetz");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Regel 1");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("L");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("K");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("R");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Regel 2");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("L");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("K");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("R");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree1);

        jToolBar1.setRollover(true);

        petriTools.add(toggleButtonPlace);
        toggleButtonPlace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/place.png"))); // NOI18N
        toggleButtonPlace.setFocusable(false);
        toggleButtonPlace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toggleButtonPlace.setMargin(new java.awt.Insets(4, 14, 4, 14));
        toggleButtonPlace.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(toggleButtonPlace);
        jToolBar1.add(jSeparator3);

        petriTools.add(toggleButtonTransition);
        toggleButtonTransition.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/transition.png"))); // NOI18N
        toggleButtonTransition.setFocusable(false);
        toggleButtonTransition.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toggleButtonTransition.setMargin(new java.awt.Insets(4, 14, 4, 14));
        toggleButtonTransition.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(toggleButtonTransition);
        jToolBar1.add(jSeparator4);

        petriTools.add(toggleButtonEdge);
        toggleButtonEdge.setFocusable(false);
        toggleButtonEdge.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toggleButtonEdge.setMargin(new java.awt.Insets(4, 14, 4, 14));
        toggleButtonEdge.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(toggleButtonEdge);

        jToolBar2.setRollover(true);
        jToolBar2.setMaximumSize(new java.awt.Dimension(32925, 32769));

        buttonStep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/step.png"))); // NOI18N
        buttonStep.setFocusable(false);
        buttonStep.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonStep.setMargin(new java.awt.Insets(4, 14, 4, 14));
        buttonStep.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(buttonStep);
        jToolBar2.add(jSeparator1);

        jSpinner1.setMaximumSize(new java.awt.Dimension(29, 20));
        jToolBar2.add(jSpinner1);

        buttonSteps.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/step.png"))); // NOI18N
        buttonSteps.setMargin(new java.awt.Insets(4, 14, 4, 14));
        jToolBar2.add(buttonSteps);
        jToolBar2.add(jSeparator2);

        toggleButtonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/play.png"))); // NOI18N
        toggleButtonPlay.setFocusable(false);
        toggleButtonPlay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toggleButtonPlay.setMargin(new java.awt.Insets(4, 14, 4, 14));
        toggleButtonPlay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(toggleButtonPlay);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );

        jInternalFrame1.setBounds(50, 30, 360, 250);
        jDesktopPane1.add(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        status.setText("Status");
        status.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        fileMenu.setText("File");

        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setText("Save As ...");
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");

        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        languageMenu.setText("Language");

        deutschMenuItem.setText("Deutsch");
        deutschMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deutschMenuItemActionPerformed(evt);
            }
        });
        languageMenu.add(deutschMenuItem);

        EnglishMenuItem.setText("English");
        EnglishMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnglishMenuItemActionPerformed(evt);
            }
        });
        languageMenu.add(EnglishMenuItem);

        menuBar.add(languageMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(status)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 691, Short.MAX_VALUE)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jToolBar2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(status)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void deutschMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deutschMenuItemActionPerformed
        initLanguage("de","DE");
    }//GEN-LAST:event_deutschMenuItemActionPerformed

    private void EnglishMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnglishMenuItemActionPerformed
        initLanguage("en","US");
    }//GEN-LAST:event_EnglishMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        try {
            String cn = UIManager.getSystemLookAndFeelClassName();
            UIManager.setLookAndFeel(cn);
        } catch (Exception e) {
            System.out.println("Exception: " + e);
        }
        new MainGUI().setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EnglishMenuItem;
    private javax.swing.JButton buttonStep;
    private javax.swing.JButton buttonSteps;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenuItem deutschMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTree jTree1;
    private javax.swing.JMenu languageMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.ButtonGroup petriTools;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JLabel status;
    private javax.swing.JToggleButton toggleButtonEdge;
    private javax.swing.JToggleButton toggleButtonPlace;
    private javax.swing.JToggleButton toggleButtonPlay;
    private javax.swing.JToggleButton toggleButtonTransition;
    // End of variables declaration//GEN-END:variables
}
