
image: ubuntu

before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends openjdk-8-jdk-headless
  - apt-get install -y --no-install-recommends ivy
  - apt-get install -y --no-install-recommends ant
  - sudo ln -s -T /usr/share/java/ivy.jar /usr/share/ant/lib/ivy.jar

build:
  script:
    - ant